[tool.poetry]
name = "Py_Solar"
version = "0.1.0"
description = ""
authors = ["Danil <danilunrandom@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^1.9.6"
mypy = "^0.770"
numpy = "^1.18.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
